project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
  output-dir: docs   
  resources:
    - documents/problem-sets/ps01/questions.pdf

execute: 
  setup: _setup.R

website:
  title: "EC 320 - Intro. Econometrics"
  favicon: UO-icon.png
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: lectures/index.qmd
        text: Lectures
      - href: documents/problem-sets/index.qmd
        text: Assignments
      - href: documents/readings/index.qmd
        text: Readings
      - href: about.qmd
        text: About Me
format:
  html:
    theme: 
      - cosmo 
      - styles.scss
    toc: true
    toc-location: left