project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
  output-dir: docs   
  resources:
    - documents/problem-sets/ps01/questions.pdf

website:
  title: "EC 320 - Intro. Econometrics"
  favicon: UO-icon.png
  navbar:
    right:
      - href: lectures/index.qmd
        text: Lectures
      - href: documents/problem-sets/index.qmd
        text: Assignments
      - href: documents/R-practice/index.qmd
        text: R Worksheets
      - href: documents/readings/index.qmd
        text: Readings

  announcement: 
    icon: clipboard2-check-fill
    dismissable: true
    content: "Welcome to my Introduction to Econometrics Course!"
    type: warning
    position: below-navbar

format:
  html:
    theme: 
      - cosmo 
      - styles.scss
    toc: true
    toc-location: left