---
name: continuous rvs
---

## Probabilities of Continuous RVs

When the variable can take on an [infinite number of possible values]{.h}, the probability it takes on any given value [must]{.hi-red} be zero.

The variable takes so many values that we cannot count all possibilities, so the probability of any one particular value is zero. 

We can use probability density functions (PDFs) to help describe continuous RVs of which there are many but we will give emphasis to two:

- Uniform Distribution
- Normal Distribution

---

## Distributions

A distribution is a function that represents all outcomes of a random variable and the corresponding probabilities. It is:

- A summary that describes the spread of data points in a set
- Essential for making inferences and assumptions from data

[Key Takeaway:]{.hi} The shape of a distribution provides valuable information of the data

---

## Uniform Distribution

The probability density function of a variable [uniformly distributed]{.h} between 0 and 2 is

\begin{align*}
    f(x) = 
        \begin{cases}
        \dfrac{1}{2} & \text{if } 0 \leq x \leq 2 \\
        0   & \text{otherwise } 
        \end{cases}
\end{align*}

```{R}
#| echo: false
#| fig-cap: ""
#| fig-align: center
#| fig-width: 16

library(ggplot2)
x <- seq(-1, 3, 0.01)
y <- seq(1, 1.5, 0.01)
z <- seq(0, 2, 0.01)

ggplot() + 
    scale_x_continuous(limits = c(-1,3), expand=c(0,0)) + 
    scale_y_continuous(limits = c(0,1), expand=c(0,0), 
                        breaks = c(0, 0.5, 1), 
                        labels = c(0, 0.5, 1)) + 
    geom_ribbon(aes(x = z, ymin = 0, ymax = 0.5), fill = "grey85", linetype = "blank") +
    geom_hline(yintercept = 0, color = "black", linewidth = 1.2) + 
    geom_vline(xintercept = -1, color = "black",  linewidth = 1.2) + 
    labs(
        x = "X",
        y = "Density"
    ) +
    theme_minimal()
```

---

## Uniform Distribution

By definition, the area under $f(x)$ is equal to 1.

The [shaded area]{.hi} illustrates the probability of the event $1 \leq X \leq 1.5$.

$$
    P(1 \leq X \leq 1.5) = (1.5 - 1) \times 0.5 = 0.25
$$

```{R}
#| echo: false
#| fig-cap: ""
#| fig-align: center
#| fig-width: 16

library(ggplot2)
x <- seq(-1, 3, 0.01)
y <- seq(1, 1.5, 0.01)
z <- seq(0, 2, 0.01)

ggplot() + 
    scale_x_continuous(limits = c(-1,3), expand=c(0,0)) + 
    scale_y_continuous(limits = c(0,1), expand=c(0,0), 
                        breaks = c(0, 0.5, 1), 
                        labels = c(0, 0.5, 1)) + 
    geom_ribbon(aes(x = z, ymin = 0, ymax = 0.5), fill = "grey85", linetype = "blank") +
    geom_ribbon(aes(x = y, ymin = 0, ymax = 0.5), fill = "lightblue", linetype = "blank") + 
    geom_vline(xintercept = 1, size = 0.35, linetype = "dashed", color = "blue") + 
    geom_vline(xintercept = 1.5, size = 0.35, linetype = "dashed", color = "blue") + 
    geom_hline(yintercept = 0, color = "black", linewidth = 1.2) + 
    geom_vline(xintercept = -1, color = "black",  linewidth = 1.2) + 
    labs(
        x = "X",
        y = "Density"
    ) +
    theme_minimal()    

```

---

## Normal Distribution

This is commonly called a ["bell curve"]{.h}. It is:

- Symmetric: Mean and median occur at the same point (i.e. no skew)
- Low-probability events are in the tails
- High-probability events are near the center

```{R}
#| label: "normal_dist_01"
#| fig-align: center
#| echo: FALSE
#| fig-width: 16

library(dplyr)

df <- tibble(x = seq(-4, 4, 0.01), y = dnorm(x)) %>%
  rbind(., tibble(x = seq(4, -4, -0.01), y = 0))
ggplot() +
  scale_x_continuous(limits = c(-4, 4), expand=c(0,0)) +
  scale_y_continuous(limits = c(0, 0.5), expand=c(0,0), breaks = c(0, 0.5), labels = c(0, 0.5)) +
  geom_polygon(data = df, aes(x, y), fill = "grey85") +
  geom_hline(yintercept = 0, color = "black", linewidth = 1.2) + 
  geom_vline(xintercept = -4, color = "black",  linewidth = 1.2) + 
  labs(
    x = "X",
    y = "Density"
  ) +
  theme_minimal()

```

---

## Normal Distribution 

The [shaded area]{.hi} illustrates the probability of the event $-2 \leq X \leq 2$ occurring

- To "find the area under the curve" we use integral calculus (or, in practice \texttt{R}).

$$
    P(-2 \leq X \leq 2) \approx 0.95
$$

```{R}
#| label: "normal_dist_02"
#| fig-align: center
#| echo: FALSE
#| fig-width: 16

library(dplyr)

df <- tibble(x = seq(-4, 4, 0.01), y = dnorm(x)) %>%
  rbind(., tibble(x = seq(4, -4, -0.01), y = 0))
ggplot() +
  scale_x_continuous(limits = c(-4, 4), expand=c(0,0)) +
  scale_y_continuous(limits = c(0, 0.5), expand=c(0,0), breaks = c(0, 0.5), labels = c(0, 0.5)) +
  geom_polygon(data = df, aes(x, y), fill = "grey85") +
  geom_polygon(data = df %>% filter(x <= qnorm(0.5 + 0.475) & x >= qnorm(0.5 - 0.475)), aes(x, y), fill = "lightblue") +
  geom_vline(xintercept = qnorm(0.5 + 0.475), size = 0.35, linetype = "dashed", color = "blue") +
  geom_vline(xintercept = qnorm(0.5 - 0.475), size = 0.35, linetype = "dashed", color = "blue") +
  geom_hline(yintercept = 0, color = "black", linewidth = 1.2) + 
  geom_vline(xintercept = -4, color = "black",  linewidth = 1.2) + 
  labs(
    x = "X",
    y = "Density"
  ) +
  theme_minimal()
``` 

---

## Normal Distribution

Continuous distribution where $x_{i}$ takes the value of any real number $(\mathbb{R})$

- The domain spans the entire real line
- Centered on the distribution mean $\mu$
 
A couple of important rules to recall:

1. The probability that the random variable takes a value $x_{i}$ is 0 for any $x_{i} \in \mathbb{R}$
2. The probability that the random variable falls between $[x_{i},x_{j}]$ range, where $x_{i} \neq x_{j}$, is the area under $p(x)$ between those two values.

The area highlighted in the previous graph represents $p(x) = 0.95$. 
The values ${-1.96,1.95}$ represent the 95\% confidence interval for $\mu$

---

## Primary Differences in Expected Values by RV Type

To find the expected value or variance of a continuous random variable instead of a discrete random variable, we just swap integrals for sums and the PDF $f(X)$ for $p_{i}$:

\vspace{1cm}

|          |   $E[X]$   |    $Var(X) = E[(X - \mu_{X})^{2}]$   |
|:---------|:--------:|:----------------------------------:|
| Discrete | $\sum_{i=1}^{n} x_{i}p_{i}$ | $\sum_{i=1}^{n} (x_{i} - \mu_{X})^{2} p_{i}$ | 
|Continuous| $\int X f(X) dX$ | $\int (X - \mu_{x})^{2} f(X) dX$ | 
